import { cn } from "@/lib/utils"

export type TourCalendarGig = {
  id: string
  date: string // YYYY-MM-DD
  eventName?: string
  venue: string
  city?: string
}

export type TourCalendarStay = {
  id: string
  city: string
  startsOn: string // YYYY-MM-DD
  endsOn: string   // YYYY-MM-DD
  color: string    // hex e.g. "#22c55e"
}

type Props = {
  startDate: string // YYYY-MM-DD
  endDate: string   // YYYY-MM-DD
  gigs: TourCalendarGig[]
  stays?: TourCalendarStay[]
  variant?: "hq" | "public"
}

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
]
const DAY_ABBREVS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

function getMonthsInRange(start: Date, end: Date): Array<{ year: number; month: number }> {
  const months: Array<{ year: number; month: number }> = []
  let cur = new Date(start.getFullYear(), start.getMonth(), 1)
  const endMonth = new Date(end.getFullYear(), end.getMonth(), 1)
  while (cur <= endMonth) {
    months.push({ year: cur.getFullYear(), month: cur.getMonth() })
    cur = new Date(cur.getFullYear(), cur.getMonth() + 1, 1)
  }
  return months
}

// Returns an array of YYYY-MM-DD strings (or null for empty cells) filling complete weeks
function generateCells(year: number, month: number): (string | null)[] {
  // Monday-first: getDay() returns 0=Sun…6=Sat; shift so 0=Mon…6=Sun
  const firstDow = (new Date(year, month, 1).getDay() + 6) % 7
  const daysInMonth = new Date(year, month + 1, 0).getDate()
  const cells: (string | null)[] = Array(firstDow).fill(null)
  for (let d = 1; d <= daysInMonth; d++) {
    cells.push(
      `${year}-${String(month + 1).padStart(2, "0")}-${String(d).padStart(2, "0")}`,
    )
  }
  while (cells.length % 7 !== 0) cells.push(null)
  return cells
}

function formatDate(dateStr: string): string {
  const [, mm, dd] = dateStr.split("-")
  const month = MONTH_NAMES[parseInt(mm) - 1]?.slice(0, 3) ?? ""
  return `${month} ${parseInt(dd)}`
}

// Supabase may return date columns with a time component ("2026-07-18T00:00:00+00:00").
// Slice to YYYY-MM-DD so Map keys match the cell keys generated by generateCells.
function toDateKey(raw: string): string {
  return raw.slice(0, 10)
}

// Convert a 6-char hex color to rgba for inline style backgrounds
function hexToRgba(hex: string, alpha: number): string {
  const r = parseInt(hex.slice(1, 3), 16)
  const g = parseInt(hex.slice(3, 5), 16)
  const b = parseInt(hex.slice(5, 7), 16)
  return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

export function TourCalendar({ startDate, endDate, gigs, stays, variant = "hq" }: Props) {
  const startD = new Date(startDate + "T00:00:00")
  const endD = new Date(endDate + "T00:00:00")
  const months = getMonthsInRange(startD, endD)
  const isPublic = variant === "public"
  const stayList = stays ?? []

  // Build date → gigs lookup (normalize to YYYY-MM-DD in case of timestamp suffix)
  const gigsByDate = new Map<string, TourCalendarGig[]>()
  for (const gig of gigs) {
    const key = toDateKey(gig.date)
    if (!gigsByDate.has(key)) gigsByDate.set(key, [])
    gigsByDate.get(key)!.push(gig)
  }

  // Sorted gig dates for mobile list
  const gigDateEntries: Array<{ date: string; gigs: TourCalendarGig[] }> = []
  for (const [date, dg] of gigsByDate.entries()) {
    gigDateEntries.push({ date, gigs: dg })
  }
  gigDateEntries.sort((a, b) => a.date.localeCompare(b.date))

  if (months.length === 0) {
    return (
      <p className={isPublic ? "text-sm text-white/40" : "text-sm text-muted-foreground/50"}>
        Invalid date range.
      </p>
    )
  }

  const emptyState = (
    <p className={cn("text-sm", isPublic ? "text-white/30" : "text-muted-foreground/40")}>
      No shows scheduled in this tour range yet.
    </p>
  )

  return (
    <div>
      {/* ── Desktop: month grid ──────────────────────────────── */}
      <div className="hidden sm:block">
        <div className="space-y-10">
          {months.map(({ year, month }) => {
            const cells = generateCells(year, month)
            const monthStr = `${year}-${String(month + 1).padStart(2, "0")}`
            const hasGigsThisMonth = gigDateEntries.some(({ date }) => date.startsWith(monthStr))

            return (
              <div key={`${year}-${month}`}>
                {/* Month header */}
                <div className="mb-3 flex items-baseline gap-2">
                  <h3 className={cn(
                    "text-[13px] font-bold uppercase tracking-[0.1em]",
                    isPublic ? "text-white/80" : "text-foreground/80",
                  )}>
                    {MONTH_NAMES[month]}
                  </h3>
                  <span className={cn(
                    "text-[11px]",
                    isPublic ? "text-white/25" : "text-muted-foreground/35",
                  )}>
                    {year}
                  </span>
                  {hasGigsThisMonth && (
                    <span className={cn(
                      "ml-auto text-[10px] font-semibold",
                      isPublic ? "text-accent/60" : "text-accent/70",
                    )}>
                      {gigDateEntries.filter(({ date }) => date.startsWith(monthStr)).reduce((n, { gigs: g }) => n + g.length, 0)} show
                      {gigDateEntries.filter(({ date }) => date.startsWith(monthStr)).reduce((n, { gigs: g }) => n + g.length, 0) !== 1 ? "s" : ""}
                    </span>
                  )}
                </div>

                {/* Weekday headers */}
                <div className="mb-1 grid grid-cols-7">
                  {DAY_ABBREVS.map((d) => (
                    <div
                      key={d}
                      className={cn(
                        "py-1 text-center text-[9px] font-semibold uppercase tracking-[0.14em]",
                        isPublic ? "text-white/20" : "text-muted-foreground/25",
                      )}
                    >
                      {d}
                    </div>
                  ))}
                </div>

                {/* Day grid */}
                <div className="grid grid-cols-7 gap-px">
                  {cells.map((date, i) => {
                    const dayGigs = date ? (gigsByDate.get(date) ?? []) : []
                    const hasGigs = dayGigs.length > 0
                    const dayNum = date ? parseInt(date.slice(8)) : null

                    // Find stays covering this date
                    const cellStays = date
                      ? stayList.filter(s => s.startsOn <= date && date <= s.endsOn)
                      : []
                    const hasStays = cellStays.length > 0

                    // Compute background style from stays.
                    // Single stay: very low-opacity fill + inset left accent bar (avoids touching
                    // the outer rounded corners that a real border-left would clip).
                    // Split stay: two subtle tinted halves separated by a thin 1px light hairline
                    // rather than a heavy dark band.
                    let stayBg: React.CSSProperties = {}
                    if (cellStays.length === 1) {
                      const c = cellStays[0].color
                      stayBg = {
                        background: hexToRgba(c, isPublic ? 0.07 : 0.05),
                        boxShadow: `inset 2px 0 0 ${hexToRgba(c, isPublic ? 0.50 : 0.38)}`,
                      }
                    } else if (cellStays.length >= 2) {
                      const c1 = cellStays[0].color
                      const c2 = cellStays[1].color
                      stayBg = {
                        background: [
                          `linear-gradient(135deg,`,
                          `  ${hexToRgba(c1, 0.09)} calc(50% - 0.5px),`,
                          `  rgba(255,255,255,0.10) calc(50% - 0.5px),`,
                          `  rgba(255,255,255,0.10) calc(50% + 0.5px),`,
                          `  ${hexToRgba(c2, 0.09)} calc(50% + 0.5px)`,
                          `)`,
                        ].join(" "),
                        // Left accent shows the first city's color
                        boxShadow: `inset 2px 0 0 ${hexToRgba(c1, isPublic ? 0.50 : 0.38)}`,
                      }
                    }

                    return (
                      <div
                        key={i}
                        style={hasStays ? stayBg : undefined}
                        className={cn(
                          "min-h-[56px] rounded p-1",
                          date === null && "pointer-events-none",
                          !hasStays && (
                            hasGigs
                              ? isPublic
                                ? "bg-accent/[0.10] ring-1 ring-inset ring-accent/20"
                                : "bg-accent/[0.07] ring-1 ring-inset ring-accent/18"
                              : date !== null
                                ? isPublic
                                  ? "bg-white/[0.025]"
                                  : "bg-secondary/20"
                                : ""
                          ),
                          hasStays && hasGigs && "ring-1 ring-inset ring-white/[0.08]",
                        )}
                      >
                        {date && (
                          <>
                            <span className={cn(
                              "block text-right text-[10px] font-medium leading-none",
                              hasGigs
                                ? isPublic ? "text-accent/80" : "text-accent"
                                : isPublic ? "text-white/22" : "text-muted-foreground/28",
                            )}>
                              {dayNum}
                            </span>

                            {/* City stay labels — intentionally subordinate to show pills */}
                            {cellStays.length > 0 && (
                              <div className="mt-0.5 space-y-px">
                                {cellStays.slice(0, 2).map((s, si) => (
                                  <p
                                    key={si}
                                    className="truncate text-[6.5px] leading-tight"
                                    style={{ color: s.color, opacity: 0.45 }}
                                  >
                                    {s.city}
                                  </p>
                                ))}
                              </div>
                            )}

                            {/* Show labels — primary visual element inside the cell */}
                            <div className="mt-0.5 space-y-px">
                              {dayGigs.slice(0, 2).map((gig, gi) => (
                                <div
                                  key={gi}
                                  className={cn(
                                    "truncate rounded px-1 py-px text-[7.5px] font-bold leading-tight",
                                    isPublic
                                      ? "bg-white/[0.12] text-white/90"
                                      : "bg-accent/[0.14] text-accent",
                                  )}
                                  title={[gig.eventName, gig.venue, gig.city].filter(Boolean).join(" · ")}
                                >
                                  {gig.eventName || gig.city || gig.venue}
                                </div>
                              ))}
                              {dayGigs.length > 2 && (
                                <div className={cn(
                                  "px-1 text-[7px] font-medium",
                                  isPublic ? "text-accent/50" : "text-accent/60",
                                )}>
                                  +{dayGigs.length - 2} more
                                </div>
                              )}
                            </div>
                          </>
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>
            )
          })}
        </div>
        {gigs.length === 0 && stayList.length === 0 && <div className="mt-6">{emptyState}</div>}
      </div>

      {/* ── Mobile: agenda list ──────────────────────────────────── */}
      <div className="sm:hidden">
        {gigs.length === 0 && stayList.length === 0 ? (
          emptyState
        ) : (
          <div className="space-y-6">
            {months.map(({ year, month }) => {
              const monthStr = `${year}-${String(month + 1).padStart(2, "0")}`
              const monthGigEntries = gigDateEntries.filter(({ date }) => date.startsWith(monthStr))

              // Stays that overlap this month
              const monthStays = stayList.filter(s => {
                const stayMonth = s.startsOn.slice(0, 7)
                const endMonth = s.endsOn.slice(0, 7)
                return stayMonth <= monthStr && endMonth >= monthStr
              })

              return (
                <div key={`mob-${year}-${month}`}>
                  <p className={cn(
                    "mb-2.5 text-[9px] font-bold uppercase tracking-[0.18em]",
                    isPublic ? "text-white/28" : "text-muted-foreground/32",
                  )}>
                    {MONTH_NAMES[month]} {year}
                  </p>

                  {/* Route / stays summary for this month */}
                  {monthStays.length > 0 && (
                    <div className="mb-3 space-y-1">
                      {monthStays.map((stay) => {
                        // Check if this stay's endsOn is another stay's startsOn (transition)
                        const incomingStay = stayList.find(
                          s => s.id !== stay.id && s.startsOn === stay.endsOn
                        )
                        const isTransition = !!incomingStay

                        return (
                          <div
                            key={stay.id}
                            className={cn(
                              "flex items-center gap-2.5 rounded-lg px-3 py-2",
                              isPublic ? "bg-white/[0.03]" : "bg-secondary/20",
                            )}
                          >
                            {/* Color dot */}
                            {isTransition && incomingStay ? (
                              <div className="flex shrink-0 items-center gap-1">
                                <span
                                  className="h-2 w-2 rounded-full shrink-0"
                                  style={{ background: stay.color }}
                                />
                                <span className={cn(
                                  "text-[9px]",
                                  isPublic ? "text-white/30" : "text-muted-foreground/40",
                                )}>→</span>
                                <span
                                  className="h-2 w-2 rounded-full shrink-0"
                                  style={{ background: incomingStay.color }}
                                />
                              </div>
                            ) : (
                              <span
                                className="h-2 w-2 rounded-full shrink-0"
                                style={{ background: stay.color }}
                              />
                            )}

                            <div className="min-w-0 flex-1">
                              {isTransition && incomingStay ? (
                                <p className={cn(
                                  "text-[11px] font-semibold",
                                  isPublic ? "text-white/70" : "text-foreground/70",
                                )}>
                                  {stay.city} → {incomingStay.city}
                                </p>
                              ) : (
                                <p className={cn(
                                  "text-[11px] font-semibold",
                                  isPublic ? "text-white/70" : "text-foreground/70",
                                )}>
                                  {stay.city}
                                </p>
                              )}
                              <p className={cn(
                                "text-[10px]",
                                isPublic ? "text-white/28" : "text-muted-foreground/38",
                              )}>
                                {formatDate(stay.startsOn)}
                                {stay.endsOn !== stay.startsOn ? ` – ${formatDate(stay.endsOn)}` : ""}
                              </p>
                            </div>
                          </div>
                        )
                      })}
                    </div>
                  )}

                  {/* Show entries */}
                  {monthGigEntries.length === 0 && monthStays.length === 0 ? (
                    <p className={cn(
                      "text-[11px]",
                      isPublic ? "text-white/18" : "text-muted-foreground/28",
                    )}>
                      No shows scheduled.
                    </p>
                  ) : monthGigEntries.length === 0 ? null : (
                    <div className="space-y-1">
                      {monthGigEntries.map(({ date, gigs: dg }) => (
                        <div
                          key={date}
                          className={cn(
                            "flex items-start gap-3 rounded-lg px-3 py-2.5",
                            isPublic ? "bg-white/[0.04]" : "bg-secondary/30",
                          )}
                        >
                          {/* "Jul 18" date label */}
                          <span className={cn(
                            "w-12 shrink-0 text-[11px] font-bold tabular-nums",
                            isPublic ? "text-accent/65" : "text-accent",
                          )}>
                            {formatDate(date)}
                          </span>
                          {/* Show(s) on this date */}
                          <div className="min-w-0 flex-1">
                            {dg.map((gig, gi) => (
                              <p
                                key={gi}
                                className={cn(
                                  "truncate text-[12px] font-semibold",
                                  gi > 0 ? "mt-1" : "",
                                  isPublic ? "text-white/85" : "text-foreground/85",
                                )}
                              >
                                {gig.eventName || gig.city || gig.venue}
                              </p>
                            ))}
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        )}
      </div>
    </div>
  )
}
